### ISSUE TITLE
Remove unused type export:

### ISSUE THREAD

**Issue by Darkchove** [Tietokilta/ilmomasiina#109]
Since you're already exporting RouterConfig through export type { RouterConfig };, you don't need to export it again using export interface IlmoConfig. You can remove the export interface IlmoConfig line to avoid redundancy.

**Comment by PurkkaKoodari** [comment]
`RouterConfig` and `IlmoConfig` are separate types (the latter contains the former) and are exported as part of the public interface of `@tietokilta/ilmomasiina-components` for potential users outside this repo.

If you wish to help with these trivial code style changes, please open a PR instead of multiple issues. In this form it feels like spam.
