### ISSUE TITLE
Consider using explicit type annotations

### ISSUE THREAD

**Issue by Darkchove** [Tietokilta/ilmomasiina#110]
While TypeScript can infer types in many cases, adding explicit type annotations to function parameters and return types can improve code readability and maintainability. You can add type annotations as necessary based on the types used in your codebase.

**Comment by PurkkaKoodari** [comment]
Type annotations are a lot like comments - they should be omitted if obvious from the context, and with a modern IDE the inferred types can be easily checked.

If you wish to help with these trivial code style changes, please open a PR with some concrete changes instead of multiple issues. In this form it feels like spam.
